
import React from 'react'
export default function Footer() {
    return (
        <div className="api-docs-bottom">
            <section id="api-docs" className="three">
                <div className="inner-content">
                    <div className="faq-section">
                        <div className="faq-title" style={{ fontSize: 30 }}>Frequently Asked Questions</div>
                        <div className="faq-border faq-top-border" />
                        <div className="question">Is commercial use allowed?</div>
                        <div className="answer">Yes, commercial use is permitted for the generated images. You may utilize these
                            images for any legal purposes. For full details, please refer to our <a href="https://deepai.org/terms-of-service/terms-of-service" className="faq-terms">Terms of
                                Service</a>.</div>
                        <div className="faq-border" />
                        <div className="question">Can I use the generated images for NFTs?</div>
                        <div className="answer">Yes, they can be used for NFTs.</div>
                        <div className="faq-border" />
                        <div className="question">Is there an API available?</div>
                        <div className="answer">Yes! To access all available APIs, please check our documentation <a href="/docs" className="faq-terms docs-link">here</a>.</div>
                        <div className="faq-border" />
                        <div className="question">Who owns the output?</div>
                        <div className="answer">The generated images are considered public domain and hence, they have no owner.
                        </div>
                        <div className="faq-border" />
                        <div className="question">Is there a copyright on the output?</div>
                        <div className="answer">The images generated by the AI are not subject to copyright.</div>
                        <div className="faq-border" />
                        <div className="question">Can I get higher resolution or higher quality images?</div>
                        <div className="answer">Currently, we do not offer images in higher resolutions or qualities. The
                            available quality will improve over time.</div>
                        <div className="faq-border" />
                        <div className="question">Is the quality of the images suitable for printing?</div>
                        <div className="answer">The quality is generally sufficient for printing smaller images. However, larger
                            prints might appear blurry.</div>
                        <div className="faq-border" />
                    </div>
                </div>
            </section>
            <dialog id="signup-modal">
                <div className="modal-body">
                </div>
                <button id="close" className="close" type="button">×</button>
            </dialog>
            <dialog id="login-modal" className="login-container">
                <div id="close-login" type="button" className="login-exit">
                    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" fill="none">
                        <path d="M11.9997 10.586L16.9497 5.63599L18.3637 7.04999L13.4137 12L18.3637 16.95L16.9497 18.364L11.9997 13.414L7.04974 18.364L5.63574 16.95L10.5857 12L5.63574 7.04999L7.04974 5.63599L11.9997 10.586Z" fill="white" />
                    </svg>
                </div>
                <div style={{ width: '95%' }}>
                    <h2 className="login-header" id="login-header-title">Login</h2>
                    <p className="please-subheader">
                        Please sign up or login with your details
                    </p>
                    <div className="options-container">
                        <div className="option login-active active" id="loginToggle" onclick="toggleAuthOption('login')">
                            Login
                        </div>
                        <div className="option signup" id="signupToggle" onclick="toggleAuthOption('signup')">
                            Sign up
                        </div>
                    </div>
                    <button className="signin-with-google" id="social-auth-google" onclick="social_login(event, 'google')">
                        <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M32 16C32 7.16344 24.8366 0 16 0C7.16344 0 0 7.16344 0 16C0 24.8366 7.16344 32 16 32C24.8366 32 32 24.8366 32 16Z" fill="white" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M23.8299 16.1823C23.8299 15.615 23.779 15.0695 23.6845 14.5459H16.1499V17.6405H20.4554C20.2699 18.6405 19.7063 19.4877 18.859 20.055V22.0623H21.4445C22.9572 20.6695 23.8299 18.6186 23.8299 16.1823Z" fill="#4285F4" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M16.1496 23.9995C18.3096 23.9995 20.1205 23.2832 21.4442 22.0614L18.8587 20.0541C18.1423 20.5341 17.226 20.8177 16.1496 20.8177C14.066 20.8177 12.3023 19.4104 11.6732 17.5195H9.00049V19.5923C10.3169 22.2068 13.0223 23.9995 16.1496 23.9995Z" fill="#34A853" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M11.6735 17.52C11.5135 17.04 11.4226 16.5272 11.4226 16C11.4226 15.4727 11.5135 14.96 11.6735 14.48V12.4072H9.00081C8.45899 13.4872 8.1499 14.709 8.1499 16C8.1499 17.2909 8.45899 18.5127 9.00081 19.5927L11.6735 17.52Z" fill="#FBBC05" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M16.1496 11.1818C17.3241 11.1818 18.3787 11.5855 19.2078 12.3782L21.5023 10.0836C20.1169 8.79273 18.306 8 16.1496 8C13.0223 8 10.3169 9.79273 9.00049 12.4073L11.6732 14.48C12.3023 12.5891 14.066 11.1818 16.1496 11.1818Z" fill="#EA4335" />
                        </svg>
                        Continue with Google
                    </button>
                    <button className="signin-with-github" id="social-auth-github" onclick="social_login(event, 'github')">
                        <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0 16C0 24.8366 7.16344 32 16 32C24.8366 32 32 24.8366 32 16C32 7.16344 24.8366 0 16 0C7.16344 0 0 7.16344 0 16Z" fill="#121212" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M15.9755 8.192C11.5719 8.192 8 11.7639 8 16.1675C8 19.6905 10.2997 22.6752 13.4312 23.7516C13.8226 23.8006 13.9694 23.5559 13.9694 23.3602C13.9694 23.1645 13.9694 22.6752 13.9694 21.9902C11.7676 22.4795 11.2783 20.9137 11.2783 20.9137C10.9358 19.984 10.3976 19.7394 10.3976 19.7394C9.66361 19.2501 10.4465 19.2501 10.4465 19.2501C11.2294 19.299 11.6697 20.0819 11.6697 20.0819C12.4037 21.3052 13.5291 20.9626 13.9694 20.7669C14.0183 20.2287 14.263 19.8862 14.4587 19.6905C12.6972 19.4948 10.8379 18.8097 10.8379 15.7272C10.8379 14.8464 11.1315 14.1614 11.6697 13.5743C11.6208 13.4275 11.3272 12.5957 11.7676 11.5192C11.7676 11.5192 12.4526 11.3235 13.9694 12.351C14.6055 12.1553 15.2905 12.1064 15.9755 12.1064C16.6606 12.1064 17.3456 12.2042 17.9817 12.351C19.4985 11.3235 20.1835 11.5192 20.1835 11.5192C20.6239 12.5957 20.3303 13.4275 20.2813 13.6232C20.7706 14.1614 21.1131 14.8954 21.1131 15.7761C21.1131 18.8587 19.2538 19.4948 17.4924 19.6905C17.7859 19.9351 18.0306 20.4244 18.0306 21.1584C18.0306 22.2348 18.0306 23.0666 18.0306 23.3602C18.0306 23.5559 18.1774 23.8006 18.5688 23.7516C21.7492 22.6752 24 19.6905 24 16.1675C23.9511 11.7639 20.3792 8.192 15.9755 8.192Z" fill="white" />
                        </svg>
                        Continue with GitHub
                    </button>
                    <div className="email-container" id="email-container-id">
                        <svg className="email-icon" xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" fill="none">
                            <path d="M22 6C22 4.9 21.1 4 20 4H4C2.9 4 2 4.9 2 6V18C2 19.1 2.9 20 4 20H20C21.1 20 22 19.1 22 18V6ZM20 6L12 11L4 6H20ZM20 18H4V8L12 13L20 8V18Z" fill="#7D7D7D" />
                        </svg>
                        <input className="input-email" id="user-email" type="text" placeholder="Enter valid email address" name="email" onkeypress="authKeyPressHandler(event)" />
                    </div>
                    <div className="password-container" id="password-container-id">
                        <svg className="lock-icon" xmlns="http://www.w3.org/2000/svg" width={27} height={24} viewBox="0 0 24 24" fill="none">
                            <path d="M12 17C13.1 17 14 16.1 14 15C14 13.9 13.1 13 12 13C10.9 13 10 13.9 10 15C10 16.1 10.9 17 12 17ZM18 8H17V6C17 3.24 14.76 1 12 1C9.24 1 7 3.24 7 6V8H6C4.9 8 4 8.9 4 10V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V10C20 8.9 19.1 8 18 8ZM8.9 6C8.9 4.29 10.29 2.9 12 2.9C13.71 2.9 15.1 4.29 15.1 6V8H8.9V6ZM18 20H6V10H18V20Z" fill="#7D7D7D" />
                        </svg>
                        <input className="input-password" id="user-password" type="password" placeholder="Enter your password" name="password" onkeypress="authKeyPressHandler(event)" />
                    </div>
                    <div className="reenter-password-container" id="reenter-password-container-id">
                        <svg className="lock-icon" xmlns="http://www.w3.org/2000/svg" width={27} height={24} viewBox="0 0 24 24" fill="none">
                            <path d="M12 17C13.1 17 14 16.1 14 15C14 13.9 13.1 13 12 13C10.9 13 10 13.9 10 15C10 16.1 10.9 17 12 17ZM18 8H17V6C17 3.24 14.76 1 12 1C9.24 1 7 3.24 7 6V8H6C4.9 8 4 8.9 4 10V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V10C20 8.9 19.1 8 18 8ZM8.9 6C8.9 4.29 10.29 2.9 12 2.9C13.71 2.9 15.1 4.29 15.1 6V8H8.9V6ZM18 20H6V10H18V20Z" fill="#7D7D7D" />
                        </svg>
                        <input className="input-password" id="confirm-user-password" type="password" placeholder="Re-enter your password" name="password" />
                        <path d="M10.125 10.5C10.0757 10.5001 10.0269 10.4905 9.98145 10.4716C9.93595 10.4527 9.89464 10.425 9.8599 10.3901L1.6099 2.14013C1.54254 2.06923 1.50555 1.97482 1.5068 1.87704C1.50805 1.77925 1.54745 1.68582 1.6166 1.61667C1.68575 1.54752 1.77918 1.50812 1.87697 1.50687C1.97475 1.50561 2.06916 1.54261 2.14006 1.60997L10.3901 9.85997C10.4425 9.91241 10.4782 9.97922 10.4926 10.0519C10.5071 10.1247 10.4996 10.2 10.4713 10.2685C10.4429 10.337 10.3949 10.3956 10.3332 10.4368C10.2716 10.478 10.1991 10.5 10.125 10.5V10.5ZM5.99201 9.00005C5.01959 9.00005 4.08185 8.71223 3.20482 8.14458C2.40631 7.62895 1.68748 6.89044 1.12592 6.01177V6.00989C1.59326 5.34028 2.10514 4.77403 2.65498 4.31747C2.65995 4.31331 2.66401 4.30817 2.66689 4.30236C2.66978 4.29655 2.67143 4.29021 2.67174 4.28374C2.67204 4.27726 2.67101 4.27079 2.66869 4.26474C2.66637 4.25868 2.66282 4.25317 2.65826 4.24856L2.19139 3.78239C2.18309 3.77403 2.17195 3.76909 2.16018 3.76857C2.14841 3.76805 2.13687 3.77198 2.12787 3.77958C1.54381 4.27177 1.0017 4.87552 0.508807 5.58239C0.424007 5.7041 0.377304 5.84828 0.374633 5.99659C0.371962 6.14491 0.413444 6.29067 0.493807 6.41536C1.11279 7.38403 1.90943 8.19989 2.79724 8.77434C3.79685 9.42192 4.87264 9.75005 5.99201 9.75005C6.59622 9.74817 7.19615 9.64861 7.76857 9.4552C7.77612 9.45264 7.7829 9.4482 7.78825 9.44229C7.79361 9.43638 7.79737 9.4292 7.79917 9.42143C7.80098 9.41367 7.80077 9.40557 7.79858 9.3979C7.79638 9.39024 7.79227 9.38326 7.78662 9.37763L7.28084 8.87184C7.2692 8.86049 7.2548 8.85235 7.23906 8.84824C7.22332 8.84413 7.20678 8.84419 7.19107 8.84841C6.79937 8.94927 6.39649 9.00022 5.99201 9.00005V9.00005ZM11.504 5.59223C10.8839 4.63317 10.0793 3.81848 9.1774 3.23606C8.17967 2.59106 7.0781 2.25005 5.99201 2.25005C5.39421 2.25111 4.80084 2.35276 4.23678 2.55075C4.22926 2.55337 4.22253 2.55785 4.21723 2.56378C4.21193 2.56972 4.20822 2.5769 4.20647 2.58466C4.20471 2.59242 4.20495 2.6005 4.20718 2.60814C4.20941 2.61578 4.21354 2.62273 4.2192 2.62833L4.72428 3.13341C4.73603 3.14496 4.75063 3.15322 4.7666 3.15733C4.78256 3.16145 4.79933 3.16128 4.81521 3.15684C5.19888 3.05306 5.59456 3.00034 5.99201 3.00005C6.94568 3.00005 7.8806 3.29138 8.77053 3.86723C9.58404 4.39223 10.3113 5.13005 10.8743 6.00005C10.8747 6.00058 10.8749 6.00124 10.8749 6.00192C10.8749 6.0026 10.8747 6.00326 10.8743 6.0038C10.4656 6.64714 9.95851 7.22234 9.37146 7.70841C9.36644 7.71255 9.36233 7.71769 9.3594 7.72351C9.35647 7.72933 9.35479 7.7357 9.35446 7.7422C9.35413 7.74871 9.35516 7.75521 9.35748 7.7613C9.3598 7.76738 9.36337 7.77292 9.36795 7.77755L9.83435 8.24372C9.84261 8.25205 9.85369 8.25699 9.8654 8.25755C9.87712 8.25812 9.88862 8.25427 9.89764 8.24677C10.5244 7.71907 11.0669 7.0988 11.5064 6.40739C11.5841 6.28555 11.6252 6.14397 11.6247 5.99947C11.6243 5.85497 11.5824 5.71363 11.504 5.59223V5.59223Z" fill="#7D7D7D">
                            <path d="M5.99999 3.75C5.83145 3.74991 5.66344 3.76878 5.49913 3.80625C5.49083 3.80797 5.48315 3.81192 5.47691 3.81766C5.47068 3.8234 5.46611 3.83072 5.46371 3.83885C5.4613 3.84698 5.46115 3.8556 5.46326 3.86381C5.46537 3.87202 5.46966 3.87951 5.47569 3.88547L8.11452 6.52359C8.12048 6.52962 8.12796 6.53392 8.13617 6.53603C8.14438 6.53814 8.15301 6.53798 8.16114 6.53558C8.16927 6.53317 8.17659 6.52861 8.18233 6.52237C8.18807 6.51613 8.19201 6.50846 8.19374 6.50016C8.26887 6.17063 8.26879 5.82842 8.19353 5.49893C8.11826 5.16944 7.96973 4.86114 7.75897 4.59692C7.54821 4.33271 7.28064 4.11937 6.97612 3.97275C6.6716 3.82613 6.33796 3.74999 5.99999 3.75V3.75ZM3.88545 5.47641C3.87949 5.47038 3.87201 5.46608 3.8638 5.46397C3.85559 5.46186 3.84696 5.46202 3.83883 5.46443C3.83071 5.46683 3.82338 5.47139 3.81764 5.47763C3.8119 5.48387 3.80796 5.49154 3.80624 5.49984C3.72124 5.87118 3.73191 6.25801 3.83725 6.62409C3.9426 6.99017 4.13916 7.32351 4.40852 7.59287C4.67788 7.86223 5.01122 8.0588 5.3773 8.16414C5.74338 8.26948 6.13022 8.28015 6.50155 8.19516C6.50985 8.19343 6.51753 8.18949 6.52376 8.18375C6.53 8.17801 6.53456 8.17069 6.53697 8.16256C6.53937 8.15443 6.53953 8.1458 6.53742 8.13759C6.53531 8.12938 6.53101 8.1219 6.52499 8.11594L3.88545 5.47641Z" fill="#7D7D7D">
                            </path>
                        </path>
                    </div>
                    <p id="user-email-error" className="bad-auth-error" />
                    <button className="button login-with-email" id="switch-to-email" onclick="authOptions('moreOptions')">Or
                        login with email</button>
                    <button className="button login-email" id="login-via-email-id" onclick="login(event)">Login</button>
                    <a className="forgot-password" id="forgot-password">
                        Forgot password?
                        <span href="javascript:void();" onclick="resetPassword(event)" className="click-here">Click here to
                            reset</span>
                    </a>
                    <button className="button goback" id="go-back-login" onclick="authOptions('lessOptions')">Go back</button>
                </div>
            </dialog>
            <dialog id="subscription-modal">
                <div id="subscription-pro-id" className="modal-small-subscription-container">
                    <div className="modal-subscriptions-container">
                        <h2 className="modal-pricing title-section">Pricing</h2>
                        <div className="modal-subscription-title-container">
                            <div className="modal-subscription-title" id="subscription-title-id">DeepAI</div>
                            <div className="modal-subscription-title pro-title" id="subscription-title-pro-id">PRO</div>
                        </div>
                        <div className="modal-subscriptions-subheader" id="subscriptions-subheader-id">DeepAI PRO member</div>
                        <div className="modal-subscription-price">
                            <div className="modal-price" id="subscription-price-id"> $4.99 </div>
                            <div className="modal-subscription-length" id="subscription-length-id">/month</div>
                        </div>
                        <button className="button modal-get-started" id="subscription-start-id" onclick="changePaymentModalState('start')">Get Started</button>
                        <div className="options-container membership-toggle" id="membership-toggle-id">
                            <div className="option member-active active" id="proToggle" onclick="toggleMembershipOption('pro')">
                                PRO
                            </div>
                            <div className="option member-active member-go" id="payGoToggle" onclick="toggleMembershipOption('go')">
                                Pay As You Go
                            </div>
                        </div>
                        <div className="modal-subscription-section" id="modal-subscription-section-id">
                            <div className="modal-overview-subscription-section">
                                <ul className="modal-overview">
                                    <li className="modal-generation-overview">
                                        <p className="modal-overview-title modal-value2">Generation Overview</p>
                                        <p className="modal-overview-title">AI Generator calls</p>
                                        <p className="modal-overview-title">AI Video Generator calls</p>
                                        <p className="modal-overview-title">AI Chat messages</p>
                                        <p className="modal-overview-title">Genius Mode messages</p>
                                        <p className="modal-overview-title">Genius Mode images</p>
                                        <p className="modal-overview-title">Genius Mode videos</p>
                                        <p className="modal-overview-title">AD-free experience</p>
                                        <p className="modal-overview-title">Private images</p>
                                    </li>
                                </ul>
                            </div>
                            <ul className="modal-overview">
                                <li>
                                    <p className="modal-value modal-value2" id="gen-calls-per" style={{ border: 'none' }}>Per month
                                    </p>
                                    <p className="modal-value" id="gen-calls-value">500</p>
                                    <p className="modal-value" id="video-calls-value">30</p>
                                    <p className="modal-value" id="chat-calls-value">1750</p>
                                    <p className="modal-value" id="genius-messages-value">60</p>
                                    <p className="modal-value" id="genius-images-value">60</p>
                                    <p className="modal-value" id="genius-videos-value">5</p>
                                    <p className="modal-value">
                                        <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <circle cx={12} cy={12} r={12} fill="white" />
                                            <path d="M10.8333 13.8503L16.1953 8.48776L17.0207 9.3126L10.8333 15.5L7.12097 11.7877L7.94581 10.9628L10.8333 13.8503Z" fill="#2D3748" />
                                        </svg>
                                    </p>
                                    <p className="modal-value">
                                        <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <circle cx={12} cy={12} r={12} fill="white" />
                                            <path d="M10.8333 13.8503L16.1953 8.48776L17.0207 9.3126L10.8333 15.5L7.12097 11.7877L7.94581 10.9628L10.8333 13.8503Z" fill="#2D3748" />
                                        </svg>
                                    </p>
                                </li>
                            </ul>
                        </div>
                        <div className="get-started-container" id="get-started-container-id">
                            <button className="button go-back-subscription" onclick="changePaymentModalState('back')">Go
                                back</button>
                            <ul id="sub-terms-pro" className="sub-terms-pro-styling">
                                <li className="subscription-terms">Includes 500 AI Image generations, 1750 AI Chat Messages, 30
                                    AI Video generations, 60 Genius Mode Messages, 60 Genius Mode Images, and 5 Genius Mode
                                    Videos per month. If you go over any of these limits, you will be charged an extra $5
                                    for that group. </li>
                                <li className="subscription-terms">For example: if you go over 500 AI images, but stay within
                                    the limits for AI Chat, Genius Mode, and Genius Mode Videos, you'll be charged $5 per
                                    additional 500 AI Image generations.</li>
                                <li className="subscription-terms">Additional Genius Mode Videos are charged at $1 per video.
                                </li>
                            </ul>
                            <ul id="sub-terms-go" className="sub-terms-go-styling">
                                <li className="subscription-terms">Includes 100 AI Image generations and 300 AI Chat Messages.
                                    If you go over any of these limits, you will have to pay as you go.</li>
                                <li className="subscription-terms">For example: if you go over 100 AI images, but stay within
                                    the limits for AI Chat, you'll have to reload on credits to generate more images. Choose
                                    from $5 - $1000. You'll only pay for what you use.</li>
                                <li className="subscription-terms">Genius Mode Videos are charged at $1 per video.</li>
                            </ul>
                            <div className="subscribe-to" id="subscribe-to-id">Subscribe to PRO using:</div>
                            <div className="payment-container" id="payment-container-pro">
                                <div className="options-container payment-options">
                                    <div className="option stripe-pay-active active" id="stripeProToggle" onclick="togglePaymentOption('stripePro')">
                                        Stripe
                                    </div>
                                    <div className="option paypal-pay" id="paypalProToggle" onclick="togglePaymentOption('paypalPro')">
                                        Paypal
                                    </div>
                                </div>
                            </div>
                            <div className="payment-container" id="payment-container-go">
                                <div className="options-container payment-options">
                                    <div className="option stripe-pay-active active" id="stripeGoToggle" onclick="togglePaymentOption('stripeGo')">
                                        Stripe
                                    </div>
                                    <div className="option paypal-pay" id="paypalGoToggle" onclick="togglePaymentOption('paypalGo')">
                                        Paypal
                                    </div>
                                </div>
                            </div>
                            <div className="dropdown-payment-amount" id="modal-dropdown-payment-amount">
                                <div className="dataset">
                                    <select id="addCreditsAmountSelect" className="dropdown-select dropdown-input-amount" name="chooseAmount">
                                        <option disabled selected value={5}>$5.00 USD</option>
                                        <option value={5}>$5.00 USD</option>
                                        <option value={10}>$10.00 USD</option>
                                        <option value={20}>$20.00 USD</option>
                                        <option value={50}>$50.00 USD</option>
                                        <option value={100}>$100.00 USD</option>
                                        <option value={200}>$200.00 USD</option>
                                        <option value={500}>$500.00 USD</option>
                                        <option value={1000}>$1000.00 USD</option>
                                    </select>
                                    <svg className="money-icon" xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" fill="none">
                                        <path d="M11.8003 10.9C9.53031 10.31 8.80031 9.7 8.80031 8.75C8.80031 7.66 9.81031 6.9 11.5003 6.9C13.2803 6.9 13.9403 7.75 14.0003 9H16.2103C16.1403 7.28 15.0903 5.7 13.0003 5.19V3H10.0003V5.16C8.06031 5.58 6.50031 6.84 6.50031 8.77C6.50031 11.08 8.41031 12.23 11.2003 12.9C13.7003 13.5 14.2003 14.38 14.2003 15.31C14.2003 16 13.7103 17.1 11.5003 17.1C9.44031 17.1 8.63031 16.18 8.52031 15H6.32031C6.44031 17.19 8.08031 18.42 10.0003 18.83V21H13.0003V18.85C14.9503 18.48 16.5003 17.35 16.5003 15.3C16.5003 12.46 14.0703 11.49 11.8003 10.9Z" fill="#7D7D7D" />
                                    </svg>
                                    <svg className="dropdown-icon" xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24">
                                        <path d="M16.59 8.58997L12 13.17L7.41 8.58997L6 9.99997L12 16L18 9.99997L16.59 8.58997Z" fill="white" />
                                    </svg>
                                </div>
                            </div>
                            <button id="stripe-pro-button-container" className="modal-get-started" onclick="window.open(deepaiProLinkUrl, '_blank')">Subscribe</button>
                            <div id="paypal-button-container-sub-popup">
                                <div className="paypal-styling" id="paypal-button-container-P-9LT69365YG9885149MPMFULA" />
                            </div>
                            <button id="stripe-go-button-container" onclick="window.open(deepaiAddCreditsLinkUrl, '_blank')" className="modal-get-started">Add Credits</button>
                            <div className="paypal-styling" id="paypal-button-container" />
                        </div>
                        <a className="modal-see-full" href="/pricing">
                            See Full Pricing Page
                            <svg xmlns="http://www.w3.org/2000/svg" width={18} height={19} viewBox="0 0 18 19" fill="none">
                                <path fillRule="evenodd" clipRule="evenodd" d="M3.8248 5.44998C3.64578 5.44998 3.47409 5.52109 3.34751 5.64768C3.22092 5.77427 3.1498 5.94595 3.1498 6.12498V13.775C3.1498 14.1476 3.4522 14.45 3.8248 14.45H11.4748C11.6538 14.45 11.8255 14.3789 11.9521 14.2523C12.0787 14.1257 12.1498 13.954 12.1498 13.775V10.175C12.1498 9.99595 12.2209 9.82427 12.3475 9.69768C12.4741 9.57109 12.6458 9.49998 12.8248 9.49998C13.0038 9.49998 13.1755 9.57109 13.3021 9.69768C13.4287 9.82427 13.4998 9.99595 13.4998 10.175V13.775C13.4998 14.312 13.2865 14.8271 12.9067 15.2069C12.5269 15.5866 12.0119 15.8 11.4748 15.8H3.8248C3.28774 15.8 2.77267 15.5866 2.39291 15.2069C2.01315 14.8271 1.7998 14.312 1.7998 13.775V6.12498C1.7998 5.58791 2.01315 5.07285 2.39291 4.69308C2.77267 4.31332 3.28774 4.09998 3.8248 4.09998H8.3248C8.50383 4.09998 8.67551 4.17109 8.8021 4.29768C8.92869 4.42427 8.9998 4.59595 8.9998 4.77498C8.9998 4.954 8.92869 5.12569 8.8021 5.25227C8.67551 5.37886 8.50383 5.44998 8.3248 5.44998H3.8248Z" fill="#C3CAD9" />
                                <path fillRule="evenodd" clipRule="evenodd" d="M5.57465 11.9777C5.63413 12.0436 5.706 12.097 5.78615 12.135C5.8663 12.1731 5.95316 12.1949 6.04176 12.1994C6.13036 12.2038 6.21897 12.1907 6.30252 12.1609C6.38606 12.131 6.4629 12.085 6.52865 12.0254L14.85 4.49605V7.02505C14.85 7.20407 14.9212 7.37576 15.0478 7.50235C15.1743 7.62893 15.346 7.70005 15.525 7.70005C15.7041 7.70005 15.8758 7.62893 16.0023 7.50235C16.1289 7.37576 16.2 7.20407 16.2 7.02505V2.97505C16.2 2.79603 16.1289 2.62434 16.0023 2.49775C15.8758 2.37116 15.7041 2.30005 15.525 2.30005H11.475C11.296 2.30005 11.1243 2.37116 10.9978 2.49775C10.8712 2.62434 10.8 2.79603 10.8 2.97505C10.8 3.15407 10.8712 3.32576 10.9978 3.45235C11.1243 3.57893 11.296 3.65005 11.475 3.65005H13.7727L5.62235 11.0246C5.55653 11.0841 5.50308 11.156 5.46505 11.2361C5.42703 11.3163 5.40517 11.4032 5.40074 11.4918C5.39631 11.5804 5.40939 11.669 5.43923 11.7525C5.46907 11.8361 5.51509 11.912 5.57465 11.9777Z" fill="#C3CAD9" />
                            </svg>
                        </a>
                    </div>
                    <button id="close-sub" className="close" type="button">×</button>
                </div>
            </dialog>
        </div>
    )
}
